require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'CloudinaryExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-cloudinary', :path => '../..'
  pod 'Cloudinary', '~> 2.0'

  # Enables Flipper.
  # INFO: Not working on M1 silicon 
  #   status: https://github.com/react-native-community/discussions-and-proposals/issues/295#issuecomment-753470834
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  #post_install do |installer|
  #  flipper_post_install(installer)
  #end
end
